import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fructus - Software",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="icon" href="/logo.png" sizes="any" />
        <meta property="image" content="/cover.png" />
      </head>
      <body className={`antialiased Poppins`}>{children}</body>
    </html>
  );
}
